MvcLibraryProject/Controllers/BookRecordController.cs
using Business.Abstract;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLibraryProject.Controllers
{
    public class BookRecordController : Controller
    {
        IBookRecordService _bookRecordService;
        IBookService _bookService;
        IMemberService _memberService;
        IStaffService _staffService;
        public BookRecordController(IBookRecordService bookRecordService, IBookService bookService,IMemberService memberService,IStaffService staffService)
        {
            _bookRecordService = bookRecordService;
            _bookService = bookService;
            _memberService = memberService;
            _staffService = staffService;
        }

        // GET: BookRecord
        [Authorize(Roles ="admin")]
        public ActionResult Index()
        {
            var value = _bookRecordService.GetDetailStatusFalse();
            return View(value);
        }
        [HttpGet]
        public ActionResult Lend()  //ödünç verme
        {
            List<SelectListItem> deger1 = (from i in _memberService.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = i.Name +" "+i.LastName,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from i in _bookService.GetByStatusTrue()
                                           select new SelectListItem
                                           {
                                               Text = i.Name,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from i in _staffService.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = i.StaffName,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult Lend(BookRecord bookRecord)
        {
            var d1 = _memberService.GetById(bookRecord.MemberId);
            var d2 = _bookService.GetById(bookRecord.BookId);
            var d3 = _staffService.GetById(bookRecord.StaffId);
            bookRecord.MemberId = d1.Id;
            bookRecord.BookId = d2.Id;
            bookRecord.StaffId = d3.Id;
            _bookRecordService.Add(bookRecord);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult AddBookRecord()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBookRecord(BookRecord bookRecord)
        {
            _bookRecordService.Add(bookRecord);
            return View();
        }
        public ActionResult GetBookRecord(int id)
        {
            var value = _bookRecordService.GetById(id);
            List<SelectListItem> deger1 = (from i in _bookService.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = i.Name,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from i in _memberService.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = i.Name + ' ' + i.LastName,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from i in _staffService.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = i.StaffName,
                                               Value = i.Id.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            DateTime d1 = DateTime.Parse(value.GivingDate.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr4 = d3.TotalDays;

            return View("GetBookRecord", value);
        }
        public ActionResult UpdateBookRecord(BookRecord bookRecord)
        {
            _bookRecordService.Update(bookRecord);
            return RedirectToAction("Index");
        }
    }
}

MvcLibraryProject/Views/BookRecord/GetBookRecord.cshtml
@model Entities.Concrete.BookRecord
@{
    ViewBag.Title = "GetBookRecord";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>GetBookRecord</h2>

@using (Html.BeginForm("UpdateBookRecord", "BookRecord", FormMethod.Post)) { 

    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>Kayıt Id</label>
        @Html.TextBoxFor(c => c.Id, new { @class = "form-control" })
        <br />
        <label>Kitap Adı</label>
        @Html.DropDownListFor(x => x.BookId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        <label>Üye Adı</label>
        @Html.DropDownListFor(x => x.MemberId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        <br />
        <label>Personel Adı</label>
        @Html.DropDownListFor(x => x.StaffId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
        <br />
        <label>Alış Tarihi</label>
        @Html.TextBoxFor(c => c.BuyingDate, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>İade Tarihi</label>
        @Html.TextBoxFor(c => c.GivingDate, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Üyenin Getirdiği Tarih</label>
        <input type="text" class="form-control" name="MemberGivingDate" value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Geç gelen gün sayısı</label>
        <input type="text" class="form-control" id="LateInput" value="@ViewBag.dgr4" />
        <br />
    </div>
    <div>
        <button class="btn btn-info" id="btn1">Ödünç Kitabı Geri Al</button>
    </div>
}

MvcLibraryProject/Views/BookRecord/Index.cshtml
@using Entities.Dto
@model List<BookRecordDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Ödünç Kitap Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th> İşlem Id</th>
        <th>Kitap Adı</th>
        <th>Üye</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.BookName</td>
            <td>@item.MemberName&nbsp;@item.MemberLastName</td>
            <td>@item.StaffName</td>
            <td>@Convert.ToDateTime(@item.BuyingDate).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(@item.GivingDate).ToString("dd/MM/yyyy")</td>
            <td><a href="/BookRecord/GetBookRecord/@item.Id" class="btn btn-default" style="background-color:#c68520">Kitabı İade Et</a></td>
        </tr>
    }
</table>

MvcLibraryProject/Views/BookRecord/Lend.cshtml
@model Entities.Concrete.BookRecord

    @{
        ViewBag.Title = "Lend";
        Layout = "~/Views/Shared/Layout.cshtml";
    }

    <h2>Lend</h2>

    <form class="form-group" method="post">
        <div style="margin-top:15px">
            <label>Üye Id</label>
            @*@Html.TextBoxFor(x => x.MemberId, new { @class = "form-control" })*@
            @Html.DropDownListFor(k => k.MemberId, (List<SelectListItem>)ViewBag.dgr1, 
           new { @class ="form-control"})
        </div>
        <div style="margin-top:15px">
            <label>Kitap Id</label>
            @Html.DropDownListFor(k => k.BookId, (List<SelectListItem>)ViewBag.dgr2,
           new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Personel ID </label>
            @Html.DropDownListFor(k => k.StaffId, (List<SelectListItem>)ViewBag.dgr3,
           new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Kitap Alış Tarihi </label>
            <input type="text" class="form-control" name="BuyingDate" value="@DateTime.Now.ToShortDateString()"/>
        </div>
        <div style="margin-top:15px">
            <label>Kitap İade Tarihi </label>
            <input type="text" class="form-control" name="GivingDate"value="@DateTime.Now.AddDays(7).ToShortDateString()" />
        </div>

        <div style="margin-top:15px">
            <button class="btn btn-info" id="btn1"> Kitabı Ödünç Ver</button>
            <input type="hidden" value="False" name="RecordStatus" />
        </div>
    </form>