MvcLibraryProject/Controllers/AnnouncementController.cs
using Business.Abstract;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLibraryProject.Controllers
{
    public class AnnouncementController : Controller
    {
        IAnnouncementService announcementService;

        public AnnouncementController(IAnnouncementService announcementService)
        {
            this.announcementService = announcementService;
        }



        // GET: Announcement
        public ActionResult Index()
        {
            var value = announcementService.GetAll();
            return View(value);
        }
        [HttpGet]
        public ActionResult NewAnnouncement()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewAnnouncement(Announcement announcement)
        {
            announcementService.Add(announcement);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAnnouncement(int id)
        {
           announcementService.Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult AnnouncementDetail(int id)
        {
            var value = announcementService.GetById(id);
            return View(value);
        }
        public ActionResult UpdateAnnouncement(Announcement announcement)
        {
            announcementService.Update(announcement);
            return RedirectToAction("Index");
        }
        
    }
}

MvcLibraryProject/Views/Announcement/AnnouncementDetail.cshtml
@model Entities.Concrete.Announcement
@{
    ViewBag.Title = "AnnouncementDetail";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Duyuru Güncelle</h2>

@using (Html.BeginForm("UpdateAnnouncement", "Announcement", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(x => x.Id)
        @Html.TextBoxFor(c => c.Id, new { @class = "form-control" })
        <br />
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control" })
        <br />
        <label>Duyuru İçerik</label>
        @Html.TextAreaFor(c => c.Detail, new { @class = "form-control" })
        <br />
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(c => c.DateTime, new { @class = "form-control" })
        <br />
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcLibraryProject/Views/Announcement/Index.cshtml
@using Entities.Concrete
@model List<Announcement>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = " ";
}

<h2>Duyurular</h2>

<table class="table table-bordered table-striped">
    <tr style="background-color:#ffd800">
        <th>Duyuru no</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var item in Model)
    {
        if(item.CategoryName == "Diger")
        {
            renk = "bg-info text-white";
        }
        if (item.CategoryName == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (item.CategoryName == "Iletisim")
        {
            renk = "bg-success text-white";
        }
        if (item.CategoryName == "Kitaplari Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }
        <tr class="@renk">
            <td>@item.Id</td>
            <td >@item.CategoryName</td>
            <td>@Convert.ToDateTime(@item.DateTime).ToString("dd/MM/yyyy")</td>
            <td><a href="/Announcement/DeleteAnnouncement/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Announcement/AnnouncementDetail/@item.Id" class="btn btn-success" style="background-color:#6e146f ;color:wheat">Detaylar</a></td>

        </tr>
    }

</table>
<a href="/Announcement/NewAnnouncement/" class="btn btn-primary">Yeni Duyuru Ekle</a>

MvcLibraryProject/Views/Announcement/NewAnnouncement.cshtml
@model Entities.Concrete.Announcement
@{
    ViewBag.Title = "NewAnnouncement";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>NewAnnouncement</h2>

<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçerik</label>
        @Html.TextBoxFor(x => x.Detail, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(x => x.DateTime, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1"> Duyuru Ekle</button>

    </div>
</form>